module Examples exposing (..)

botc = """Noble,townsfolk,+starting info,,,,,,,,,,,,,,,,,,,,
Investigator,townsfolk,+starting info,,,,,,,,,,,,,,,,,,,,
Chef,townsfolk,+starting info,,,,,,,,,,,,,,,,,,,,
Washerwoman,townsfolk,+starting info,,,,,,,,,,,,,,,,,,,,
Clockmaker,townsfolk,+starting info,,,,,,,,,,,,,,,,,-demon can move,,,
Librarian,townsfolk,+starting info,,,,,,,,,,,,,,,,,,,,
Grandmother,townsfolk,+starting info,,,,,,,,,-protects from demon kill,,,,,,,,,,,
Bounty Hunter,townsfolk,+starting info,,,,,,,,,,,,,,,,,-demon can move,,,
Pixie,townsfolk,+starting info,,,,,,,,,,,,,,,,,,,,
Empath,townsfolk,,,,,,,,,,,,,,,,,,,,,
Sailor,townsfolk,,-starting info,,-once per game,+drunkenness or poisoning,,+immunity to demon kill,,,,,,+protection from execution,-protection from execution,,,,,,,
General,townsfolk,,,,,,,,,,,,,,,,,,,,,
Preacher,townsfolk,,,,,,,,,,,,,,,,,,,,,
Chambermaid,townsfolk,,,,,,,,,,,,,,,,,,-demon can move,,,
Balloonist,townsfolk,,,,,,,,,,,,,,,,,,-demon can move,,,
King,townsfolk,,,,,,,,,,-protects from demon kill,,,,,,,,,,+free bluffs,
Dreamer,townsfolk,,,,,,,,,,,,,,,,,,-demon can move,,,
Fortune Teller,townsfolk,,,,,,,,,,,,,,,,,,-demon can move,,,
Mathematician,townsfolk,,,,,,-drunkenness or poisoning,,-immunity to demon kill,,,,,,,,,,,,,
Snake Charmer,townsfolk,,,,,+drunkenness or poisoning,,,,,,,,,,,,+demon can move,-demon can move,,,
Cult Leader,townsfolk,,,,,,,,,,,,,,,,,,,,,
Flowergirl,townsfolk,,,,,,,,,,,,,,,,,,-demon can move,,,
Town Crier,townsfolk,,,,,,,,,,,,,,,,,,,,,
Oracle,townsfolk,,,,,,,,,,,,,,,,,,,,,
Undertaker,townsfolk,,-starting info,,,,,,,,,,,,,,,,-demon can move,,,
Innkeeper,townsfolk,,-starting info,,-once per game,+drunkenness or poisoning,,,,+protects from demon kill,,,,,,,,,,,,
Gambler,townsfolk,,,,,,,,,,-protects from demon kill,,,,,,,,,,,
Monk,townsfolk,,,,,,,,,+protects from demon kill,,,,,,,,,,,,
Lycanthrope,townsfolk,,-starting info,,,,,,,+protects from demon kill,,,,,,,,,,,,
Exorcist,townsfolk,,,,,,,,,,,,,,,,,,-demon can move,,,
Gossip,townsfolk,,,,,,,,,,-protects from demon kill,,,,,,,,,,,
Savant,townsfolk,,,,,,,,,,,,,,,,,,,,,
Amnesiac,townsfolk,,,,,,,,,,,+approaches storyteller during day,-approaches storyteller during day,,,,,,,,,
Juggler,townsfolk,,,+once per game,,,,,,,-protects from demon kill,,,,,,,,,,,
Nightwatchman,townsfolk,,,+once per game,,,,,,,,,,,,,,,,,,
Engineer,townsfolk,,,+once per game,,,,,,,,,,,,,,,,,,
Artist,townsfolk,,,+once per game,,,,,,,,+approaches storyteller during day,-approaches storyteller during day,,,,,,,,,
Courtier,townsfolk,,,+once per game,,+drunkenness or poisoning,,,,,,,,,,,,,,,,
Fisherman,townsfolk,,,+once per game,,,,,,,,+approaches storyteller during day,-approaches storyteller during day,,,,,,,,,
Slayer,townsfolk,,,+once per game,,,,,,,,,,,,,,,-demon can move,,,
Professor,townsfolk,,-starting info,+once per game,-once per game,,,,,,,,,,,,,,,,,
Seamstress,townsfolk,,,+once per game,,,,,,,,,,,,,,,,,,
Philosopher,townsfolk,,-starting info,+once per game,-once per game,+drunkenness or poisoning,,,,,,,,,,,,,,,,
Huntsman,townsfolk,,,+once per game,,,,,,,,,,,,,,,,,+free bluffs,
Soldier,townsfolk,,,,,,,+immunity to demon kill,,,,,,,,,,,,,,
Fool,townsfolk,,,+once per game,,,,+immunity to demon kill,,,,,,+protection from execution,-protection from execution,,,,,,,
Pacifist,townsfolk,,,,,,,,,,,,,+protection from execution,-protection from execution,,,,,,,
Alchemist,townsfolk,,,,,,,,,,,,,,,,,,,,,
Tea Lady,townsfolk,,,,,,,,,,,,,+protection from execution,-protection from execution,,,,,,,
Sage,townsfolk,,,,,,,,,,,,,,,,,,-demon can move,,,
Farmer,townsfolk,,-starting info,,,,,,,,,,,,,,,,,,,
Magician,townsfolk,,,,,,,,,,,,,,,,,,-demon can move,,+free bluffs,-free bluffs
Ravenkeeper,townsfolk,,,,,,,,,,,,,,,,,,-demon can move,,,
Choirboy,townsfolk,,,,,,,,,,,,,,,,,,-demon can move,,,
Virgin,townsfolk,,-starting info,,,,,,,,,,,,,,,,,,,
Poppy Grower,townsfolk,,,,,,,,,,,,,,,,,,-demon can move,,+free bluffs,-free bluffs
Minstrel,townsfolk,,,,,,,,,,,,,,,,,,,,,
Mayor,townsfolk,,,,,,,+immunity to demon kill,,,,,,,,,,,,,,
Atheist,townsfolk,,,,,,,,,,,,,,,,,,,,+free bluffs,
Cannibal,townsfolk,,-starting info,,-once per game,+drunkenness or poisoning,,,,,,,,,,,,,,,,
Snitch,outsider,+starting info,,,,,,,,,,,,,,,-outsiders want to hide,,,,+free bluffs,
Butler,outsider,,,,,,,,,,,,,,,,-outsiders want to hide,,,,,
Goon,outsider,,,,,+drunkenness or poisoning,,,,,,,,,,,,,,,,
Acrobat,outsider,,,,,,-drunkenness or poisoning,,,,,,,,,,-outsiders want to hide,,,,,
Puzzlemaster,outsider,,,+once per game,,+drunkenness or poisoning,,,,,,+approaches storyteller during day,-approaches storyteller during day,,,,,,-demon can move,,,
Tinker,outsider,,,,,,,,,,,,,,,,-outsiders want to hide,,,,,
Saint,outsider,,,,,,,,,,,,,,,,-outsiders want to hide,,,,,
Sweetheart,outsider,,,,,+drunkenness or poisoning,,,,,,,,,,,,,,,,
Recluse,outsider,,,,,,,,,,,,,,,,-outsiders want to hide,,,,,
Mutant,outsider,,,,,,,,,,,,,,,,,,,,,
Heretic,outsider,,,,,,,,,,,,,,,,,,,,,
Damsel,outsider,,,,,,,,,,,,,,,,,,,,+free bluffs,
Klutz,outsider,,,,,,,,,,,,,,,,,,,,,
Drunk,outsider,,,,,,,,,,,,,,,,,,,,,
Golem,outsider,,,+once per game,,,,,,,,,,,,,-outsiders want to hide,,,,,
Moonchild,outsider,,,,,,,,,,,,,,,,,,,,,
Barber,outsider,,,,,,,,,,,,,,,,,+demon can move,-demon can move,,,
Politician,outsider,,,,,,,,,,,,,,,,,,,,,
Lunatic,outsider,,,,,,,,,,,,,,,,,,,,+free bluffs,
Godfather,minion,,,,,,,,,,,,,,,,,,,,+free bluffs,
Widow,minion,,-starting info,,,+drunkenness or poisoning,,,,,,,,,,,,,,,+free bluffs,
Poisoner,minion,,,,,+drunkenness or poisoning,,,,,,,,,,,,,,,,
Devil's Advocate,minion,,,,,,,,,,,,,+protection from execution,-protection from execution,,,,,,,
Witch,minion,,,,,,,,,,,,,,,,,,,,,
Spy,minion,,,,,,,,,,,,,,,,,,,,+free bluffs,
Cerenovus,minion,,,,,,,,,,,,,,,,,,,,,
Fearmonger,minion,,,,,,,,,,,,,,,,,,,,,
Pit-Hag,minion,,,,,,,,,,,,,,,,,+demon can move,-demon can move,,,
Psychopath,minion,,,,,,,,,,,,,,,,,,,,,
Assassin,minion,,,,,,,,,,,,,,,,,,,,,
Baron,minion,,,,,,,,,,,,,,,,,,,,,
Mezepheles,minion,,,,,,,,,,,,,,,,,,,,,
Goblin,minion,,,,,,,,,,,,,,,,,,,,+free bluffs,
Scarlet Woman,minion,,,,,,,,,,,,,,,,,+demon can move,-demon can move,,,
Mastermind,minion,,,,,,,,,,,,,,,,,,,,,
Evil Twin,minion,,,,,,,,,,,,,,,,,,,,+free bluffs,
Boomdandy,minion,,,,,,,,,,,,,,,,,,,,,
Marionette,minion,,,,,,,,,,,,,,,,,,,,+free bluffs,
Pukka,demon,,,,,+drunkenness or poisoning,,,-immunity to demon kill,,,,,,,,,,,,,
Lil' Monsta,demon,,,,,,,,,,,,,,,,,+demon can move,-demon can move,,,-free bluffs
Lleech,demon,,,,,+drunkenness or poisoning,,,,,,,,+protection from execution,-protection from execution,,,,,,,
No Dashii,demon,,,,,+drunkenness or poisoning,,,,,,,,,,,,,,,,
Imp,demon,,,,,,,,,,,,,,,,,+demon can move,-demon can move,,,
Shabaloth,demon,,-starting info,,,,,,,,,,,,,,,,,,,
Po,demon,,,,,,,,,,,,,,,,,,,,,
Zombuul,demon,,,,,,,,,,,,,,,,,,,,,
Al-Hadikhia,demon,,-starting info,,,,,,-immunity to demon kill,,,,,,,,,,,,,
Vigormortis,demon,,,,,+drunkenness or poisoning,,,,,,,,,,,,,,,,
Fang Gu,demon,,,,,,,,,,,,,,,+outsiders want to hide,,+demon can move,-demon can move,,,
Vortox,demon,,-starting info,,,,,,,,,,,,,,,,,,,
Legion,demon,,,,,,,,,,,,,,,,,,-demon can move,,,-free bluffs
Leviathan,demon,,,,,,,,,,,,,,,,,,,,,
Riot,demon,,-starting info,,,,,,,,,,,,,,,,,,,
"""

spirit_island = """Lightning's Swift Strike,LOW,,,,,,,+AOE damage,,,,,,,,,,,,,,,,,,,,,,,
River Surges in Sunlight,LOW,,,,,,,,,,,+Gives energy,,,,,,,,,, ,,,,,,+Pushes invaders,,,
Shadows Flicker Like Flame,LOW,,,,,,,,,,,,,,,,,,,,, ,,,-Innate dahan manipulation,,,+Pushes invaders,,,
Vital Strength of the Earth,LOW,,,,,,,,,,,,,,-Gives elements,,,+Skips actions,,,, ,,,-Innate dahan manipulation,,,,,+Blight manipulation,
A Spread of Rampant Green,MODERATE,,,,,,,+AOE damage,,,,,,,,+Gives presence,-Gives presence,+Skips actions,,+Destroys presence,, ,,,,,,+Pushes invaders,,+Blight manipulation,
Thunderspeaker,MODERATE,,,,,,,,,,,,,,,,,,,,,,,+Innate dahan manipulation,-Innate dahan manipulation,,,,,,
Bringer of Dreams and Nightmares,HIGH,,,,,,,,,,,,,+Gives elements,,,,,,,, ,,,-Innate dahan manipulation,,,+Pushes invaders,,,
Ocean's Hungry Grasp,HIGH,,,,,,,,,,,+Gives energy,-Gives energy,,,,,,,,, ,,,,,,+Pushes invaders,-Pushes invaders,,
Keeper of the Forbidden Wilds,MODERATE,,,,,+Adds wilds,-Adds wilds,,,,-Presence movement,+Gives energy,-Gives energy,,,,-Gives presence,,,,, ,,+Innate dahan manipulation,,,,+Pushes invaders,,+Blight manipulation,-Blight manipulation
Sharp Fangs Behind the Leaves,MODERATE,,,,,,,,,,,,,,,,,+Skips actions,,+Destroys presence,,+Beast manipulation,-Beast manipulation,,,,,+Pushes invaders,,,
Heart of the Wildfire,HIGH,,,,,,,,,,-Presence movement,+Gives energy,-Gives energy,,-Gives elements,,-Gives presence,,,,,+Beast manipulation,,+Innate dahan manipulation,,,,+Pushes invaders,,+Blight manipulation,-Blight manipulation
Serpent Slumbering Beneath the Island,HIGH,,,,,,,,,,-Presence movement,+Gives energy,,+Gives elements,,+Gives presence,-Gives presence,,,,, ,,,,,,+Pushes invaders,,,
Grinning Trickster Stirs Up Trouble,MODERATE,,,,,,,,,,,,,,,,,,,,,+Beast manipulation,-Beast manipulation,+Innate dahan manipulation,,+Adds strife,-Adds strife,,,,-Blight manipulation
Lure of the Deep Wilderness,MODERATE,+Adds disease,-Adds disease,+Adds badlands,-Adds badlands,+Adds wilds,-Adds wilds,,-AOE damage,,,,,,,,,,,,,+Beast manipulation,-Beast manipulation,,,,,,,,
Many Minds Move as One,MODERATE,,,,,,,,,+Presence movement,,,,,,,,,,,,+Beast manipulation,-Beast manipulation,,,,,+Pushes invaders,,,
Shifting Memory of Ages,MODERATE,,,,,,,,,,,,,+Gives elements,,,,,,,, ,,,,,,,,,
Stone's Unyielding Defiance,MODERATE,,,+Adds badlands,,,,,,,,,-Gives energy,,-Gives elements,,-Gives presence,,,,, ,,,,,,,,+Blight manipulation,-Blight manipulation
Volcano Looming High,MODERATE,,,,,,,,,,,,,,,,-Gives presence,,,+Destroys presence,,,,+Innate dahan manipulation,,,,,,,-Blight manipulation
Shroud of Silent Mist,HIGH,,,,,,,,,,,,,,,,,,,,, ,,,,,,,,,
Vengeance as a Burning Plague,HIGH,+Adds disease,-Adds disease,,,,,,,,,,,,,,,,,,-Destroys presence, ,,,,,,,,,
Fractured Days Split the Sky,VERY HIGH,,,,,,,,,,,,,,,,,+Skips actions,-Skips actions,,, ,,,,,,,,,
Starlight Seeks Its Form,VERY HIGH,,,,,,,,,,,,,,,,,,,,, ,,,,,,,,,
Downpour Drenches the World,HIGH,,,,,,,,,,,,,,,,,,,,, ,,,,,,,,,
Finder of Paths Unseen,VERY HIGH,,,,,,,,-AOE damage,,,,,,,,,,,,, ,,,,,,,,,
Devouring Teeth Lurk Underfoot,LOW,,,,,,,,,,,,,,,,,,,,, ,,,,,,,,,
Eyes Watch from the Trees,LOW,,,,,,,,,,,,,,,,,,,,, ,,,,,,,,,
Fathomless Mud of the Swamp,LOW,,,,,,,,,,,,,,,,,,,,, ,,,,,,,,,
Rising Heat of Stone and Sand,LOW,,,,,,,,,,,,,,,,,,,,, ,,,,,,,,,
Sun-Bright Whirlwind,LOW,,,,,,,,,,,,,,,,,,,,, ,,,,,,,,,
Ember-Eyed Behemoth,MODERATE,,,,,,,,,,,,,,,,,,,,, ,,,,,,,,,
Towering Roots of the Jungle,MODERATE,,,,,,,,,,,,,,,,,,,,, ,,,,,,,,,
Hearth-Vigil,MODERATE,,,,,,,,,,,,,,,,,,,,, ,,,,,,,,,
Breath of Darkness Down Your Spine,HIGH,,,,,,,,-AOE damage,+Presence movement,,,,,,,,,,,, ,,,,,,,,,
Relentless Gaze of the Sun,HIGH,,,,,,,,,,,,,,,,,,,+Destroys presence,, ,,,,,,,,,
Wandering Voice Keens Delirium,HIGH,,,,,,,,,,,,,,,,,,,,, ,,,,+Adds strife,,,,,
Wounded Waters Bleeding,HIGH,,,,,,,,,,,,,,,,,,,+Destroys presence,,+Beast manipulation,-Beast manipulation,+Innate dahan manipulation,-Innate dahan manipulation,,,,,,
Dances Up Earthquakes,VERY HIGH,,,,,,,,,,,,,,,,,,,,, ,,,,,,,,,
"""