module Examples exposing (..)

botc = """Role,Type,Starting info role (good),Once per game role (good),Drunkenness or Poisoning,Demon kill immunity,Demon kill protection,Reason to visit storyteller,Explanation for failed execution,Reason for outsiders to hide,Demon mobility / Multiple demons,Free evil bluffs
Noble,Townsfolk,+,,,,,,,,,
Investigator,Townsfolk,+,,,,,,,,,
Chef,Townsfolk,+,,,,,,,,,
Washerwoman,Townsfolk,+,,,,,,,,,
Clockmaker,Townsfolk,+,,,,,,,,/,
Librarian,Townsfolk,+,,,,,,,,,
Grandmother,Townsfolk,+,,,,,,,,,
Bounty Hunter,Townsfolk,+,,,,,,,,/,
Pixie,Townsfolk,+,,,,,,,,,
Empath,Townsfolk,,,,,,,,,,
Sailor,Townsfolk,/,/,++,+,,,++//,,,
General,Townsfolk,,,,,,,,,,
Preacher,Townsfolk,,,,,,,,,,
Chambermaid,Townsfolk,,,,,,,,,/,
Balloonist,Townsfolk,,,,,,,,,/,
King,Townsfolk,,,,,,,,,,++
Dreamer,Townsfolk,,,,,,,,,/,
Fortune Teller,Townsfolk,,,,,,,,,/,
Mathematician,Townsfolk,,,//,//,,,,,,
Snake Charmer,Townsfolk,,,+,,,,,,+/,
Cult Leader,Townsfolk,,,,,,,,,,
Flowergirl,Townsfolk,,,,,,,,,/,
Town Crier,Townsfolk,,,,,,,,,,
Oracle,Townsfolk,,,,,,,,,,
Undertaker,Townsfolk,/,,,,,,,,/,
Innkeeper,Townsfolk,/,/,++,,++,,,,,
Gambler,Townsfolk,,,,,///,,,,,
Monk,Townsfolk,,,,,+,,,,,
Lycanthrope,Townsfolk,/,,,,++,,,,,
Exorcist,Townsfolk,,,,,,,,,/,
Gossip,Townsfolk,,,,,/,,,,,
Savant,Townsfolk,,,,,,,,,,
Amnesiac,Townsfolk,,,,,,+/,,,,
Juggler,Townsfolk,,+,,,/,,,,,
Nightwatchman,Townsfolk,,+,,,,,,,,
Engineer,Townsfolk,,+,,,,,,,,
Artist,Townsfolk,,+,,,,+/,,,,
Courtier,Townsfolk,,+,+,,,,,,,
Fisherman,Townsfolk,,+,,,,+/,,,,
Slayer,Townsfolk,,+,,,,,,,//,
Professor,Townsfolk,/,+/,,,,,,,,
Seamstress,Townsfolk,,+,,,,,,,,
Philosopher,Townsfolk,/,+/,+,,,,,,,
Huntsman,Townsfolk,,+,,,,,,,,++
Soldier,Townsfolk,,,,+,,,,,,
Fool,Townsfolk,,+,,+,,,+/,,,
Pacifist,Townsfolk,,,,,,,+/,,,
Alchemist,Townsfolk,,,,,,,,,,
Tea Lady,Townsfolk,,,,,,,+/,,,
Sage,Townsfolk,,,,,,,,,//,
Farmer,Townsfolk,,,,,,,,,,
Magician,Townsfolk,,,,,,,,,/,+///
Ravenkeeper,Townsfolk,,,,,,,,,/,
Choirboy,Townsfolk,,,,,,,,,///,
Virgin,Townsfolk,,,,,,,,,,
Poppy Grower,Townsfolk,,,,,,,,,/,+///
Minstrel,Townsfolk,,,,,,,,,,
Mayor,Townsfolk,,,,+,,,,,,
Atheist,Townsfolk,,,,,,,,,,+
Cannibal,Townsfolk,/,/,+,,,,,,,
Snitch,Outsider,,,,,,,,/,,++
Butler,Outsider,,,,,,,,/,,
Goon,Outsider,,,+,,,,,,,
Acrobat,Outsider,,,/,,,,,/,,
Puzzlemaster,Outsider,,+,+,,,+/,,,/,
Tinker,Outsider,,,,,,,,/,,
Saint,Outsider,,,,,,,,//,,
Sweetheart,Outsider,,,+,,,,,,,
Recluse,Outsider,,,,,,,,/,,
Mutant,Outsider,,,,,,,,,,
Heretic,Outsider,,,,,,,,,,
Damsel,Outsider,,,,,,,,,,+
Klutz,Outsider,,,,,,,,,,
Drunk,Outsider,,,,,,,,,,
Golem,Outsider,,+,,,,,,/,,
Moonchild,Outsider,,,,,,,,,,
Barber,Outsider,,,,,,,,,+/,
Politician,Outsider,,,,,,,,,,
Lunatic,Outsider,,,,,,,,,,+
Godfather,Minion,,,,,,,,+,,+
Widow,Minion,/,,+,,,,,,,+++
Poisoner,Minion,,,++,,,,,,,
Devil's Advocate,Minion,,,,,,,+/,,,
Witch,Minion,,,,,,,,,,
Spy,Minion,,,,,,,,,,+++
Cerenovus,Minion,,,,,,,,,,
Fearmonger,Minion,,,,,,,,,,
Pit-Hag,Minion,,,,,,,,,+/,
Psychopath,Minion,,,,,,,,,,
Assassin,Minion,,,,,,,,,,
Baron,Minion,,,,,,,,,,
Mezepheles,Minion,,,,,,,,,,
Goblin,Minion,,,,,,,,,,+
Scarlet Woman,Minion,,,,,,,,,+/,
Mastermind,Minion,,,,,,,,,,
Evil Twin,Minion,,,,,,,,,,+
Boomdandy,Minion,,,,,,,,,,
Marionette,Minion,,,,,,,,,,+
Pukka,Demon,,,+,/,,,,,,
Lil' Monsta,Demon,,,,,,,,,+++/,///
Lleech,Demon,,,+,,,,+/,,,
No Dashii,Demon,,,++,,,,,,,
Imp,Demon,,,,,,,,,+/,
Shabaloth,Demon,/,,,,,,,,,
Po,Demon,,,,,,,,,,
Zombuul,Demon,,,,,,,,,,
Al-Hadikhia,Demon,/,,,//,,,,,,
Vigormortis,Demon,,,+,,,,,,,
Fang Gu,Demon,,,,,,,,+++,+/,
Vortox,Demon,/,,,,,,,,,
Legion,Demon,,,,,,,,,+/,///
Leviathan,Demon,,,,,,,,,,
Riot,Demon,///,,,,,,,,,
"""

duelyst2 = """Name,Type,Tribe,Damage buff for minions,Cheap minion summon,Equipped Artifact,MECHAZ0R Progress,Provoke,Opening Gambit,Damage to friendly minions,Damage to friendly general,Spell Damage Immunity
Dragonlark,Minion,,,++,,,,,,,
Fire Spitter,Minion,,,++,,,,,,,
Komodo Scavenger,Minion,,,++,//,,,,,,
Planar Scout,Minion,,,++,,,,,,,
Helm of MECHAZ0R,Minion,Mech,,++,,++//,,,,,
Swamp Entangler,Minion,,/,++,,,+,,,,
Maw,Minion,,,++,,,,+,+,+,
Moebius,Minion,,,+,,,,+,,,
Prophet of the White Palm,Minion,,,++,,,,+,,,++
Silvertongue Corsair,Minion,,///,+,,,/,,,,
Ephemeral Shroud,Minion,,,+,,,,+,,,
Vale Hunter,Minion,,,+,,,,,,,
Manaforger,Minion,Arcanyst,,+,,,,,,,
Wings of MECHAZ0R,Minion,Mech,,+,,++//,,,,,
Rock Pulverizer,Minion,,,+,,,+,,,,
Bluetip Scorpion,Minion,,/,+,,,,,,,
Primus Fist,Minion,,+,+,,,,+,,,
Golem Metallurgist,Minion,Golem,,+,,,,,,,
Piercing Mantis,Minion,,+,+,,,/,,,,
Skyrock Golem,Minion,Golem,,+,,,,,,,
Azure Horn Shaman,Minion,,,+,,,,,,,
Flameblood Warlock,Minion,,,+,,,,+,,+,
Bloodtear Alchemist,Minion,,,+,,,,+,+,+,
Crossbones,Minion,,,+,,,,,,,
Rust Crawler,Minion,,,+,,,,+,,,
Healing Mystic,Minion,,,+,,,,+,,,
Aethermaster,Minion,Arcanyst,,+,,,,,,,
Ghost Lynx,Minion,,,+,,,,+,,,
Jaxi,Minion,,,+,,,,,,,
Araki Headhunter,Minion,,,+,,,,///,,,
Dreamgazer,Minion,,,++,,,,,,+,
Mana Artificer,Minion,,,+,,,,,,,
Double Agent,Minion,,,+,,,,+,,,
Saberspine Tiger,Minion,,,,,,,,,,
Blaze Hound,Minion,,,,,,,,,,
Sand Burrower,Minion,,,,,,,,,,
Repulsor Beast,Minion,,,,,,,+,,,
Bloodshard Golem,Minion,Golem,,,,,,,,,
Sun Seer,Minion,Arcanyst,//,,,,,,,,
Prismatic Illusionist,Minion,Arcanyst,,,,,,,,,
Alcuin Loremaster,Minion,Arcanyst,,,,,,+,,,
Cannon of MECHAZ0R,Minion,Mech,,,,++//,,,,,
Sword of MECHAZ0R,Minion,Mech,,,,++//,,,,,
Shield Oracle,Minion,,,,,,,,,,
Crimson Oculus,Minion,,,,,,,,,,
Putrid Dreadflayer,Minion,,,,,,,,,,
Golem Vanguard,Minion,Golem,,,,,++,,,,
Sarlac the Eternal,Minion,,,+++,,,,,,,
Mirkblood Devourer,Minion,,+,/,,,,,,,
Sojourner,Minion,,,,,,,+,,,
Sworn Avenger,Minion,,,,,,,,,//,
Venom Toth,Minion,,,,,,,,,,
Chaos Elemental,Minion,,,,,,,,/,,
Mindwarper,Minion,Arcanyst,,,,,,,,,
Syvrel the Exile,Minion,,,,,,,,,,
Spelljammer,Minion,,,,,,,,,,
Void Hunter,Minion,,,,,,,,,,
Lady Locke,Minion,,,///,,,++,,,,
Wind Runner,Minion,,+,,,,,,,,
Mogwai,Minion,,/,,,,,+,,,
Wings of Paradise,Minion,,,,,,,,,,
Owlbeast Adept,Minion,Arcanyst,,,,,,,,,
Chew-e,Minion,Mech,/,,,,/,,,,
Riftwalker,Minion,,,,,,,+,+,+,
Capricious Marauder,Minion,,,,,,/,,,,
Metaltooth,Minion,Mech,,,,,,,,,
Owlbeast Prophet,Minion,Arcanyst,,,,,,+,+,+,
Isbee's Monument,Minion,Structure,,,,,,,,,
Owlbeast Sage,Minion,Arcanyst,,,,,,,,,
Lightbender,Minion,,,,,,,+,,,
Chassis of MECHAZ0R,Minion,Mech,,,,++//,,,,,
Primus Shieldmaster,Minion,,,,,,+,,,,
Cinderbeast,Minion,,,,,,,,,+,
Thorn Needler,Minion,,,,,,,,//,,
Young Flamewing,Minion,,,,,,,,,,
Frostbone Naga,Minion,,,,,,,+,+,+,
Silhouette Tracer,Minion,,,,,,,+,,,
Artifact Hunter,Minion,,,,+,,,+,,,
Dioltas,Minion,,,,,,,,,,
Hailstone Golem,Minion,Golem,,,,,,,,,
Captain Hank Hart,Minion,,/,,,,,,,,
Purgatos The Realmkeeper,Minion,,,,,,,,,,
Songweaver,Minion,,,,/,,,,,,
Emerald Rejuvenator,Minion,,,,,,,+,,,
Black Locust,Minion,,,,,,,,,,
Sun Elemental,Minion,,,,,,,,,,
Keeper of the Vale,Minion,,,++,,,,+,,,
White Widow,Minion,,,,,,,,,,
Hollow Grovekeeper,Minion,,,,,,++,+,,,
Tethermancer,Minion,,,,,,,+,,,
Pummy the Stormchaser,Minion,,,,,,/,,,,
Decapotheosis,Minion,,///,++,,,,,,,
Temporal Sage Lily,Minion,Arcanyst,,,,,,+,,,
Krazed,Minion,,/,,,,,,,,
Slothguard Letharus,Minion,,+,,,,+/,+,,,
Twilight Sorcerer,Minion,Arcanyst,,,,,,+,,,
Brightmoss Golem,Minion,Golem,,,,,,,,,
Rogue Warden,Minion,,,,,,,,,,
Sworn Defender,Minion,,,,,,+,+,,,
Dagger Kiri,Minion,,,,,,,,,,
Dancing Blades,Minion,,,,,,,+,+,,
Lux Ignis,Minion,,,,,,/,,,,
Ash Mephyt,Minion,,,+,,,,+,,,
The High Hand,Minion,,,,,,,+,,,
Zen'Rui the Blightspawned,Minion,,,,,,,+,,,
Flame Acolyte,Minion,Arcanyst,,,,,,,,,
Psionic Resonator,Minion,Arcanyst,,,,,/,,,,
Stormmetal Golem,Minion,Golem,,,,,,,,,
Serpenti,Minion,,,,,,,,,,
Storm Aratha,Minion,,,,,,/,,,,
Archon Spellbinder,Minion,Arcanyst,,,,,,,,,
Deathblighter,Minion,,,,,,,,,,
First Sword of Akrane,Minion,,+,,,,,,,,
Eclipse,Minion,Arcanyst,,,,,,,//,,
Rook,Minion,,,,,,,+,,,
Bonereaper,Minion,,,,,,+,,,,
War Talon,Minion,,+,,,,,,,,
Dezark,Minion,,,,,,,,,,
Boulder Breacher,Minion,Golem,,,,,,+,+,+,
Dragonbone Golem,Minion,Golem,,,,,,,,,
Whistling Blade,Minion,,,,,,,,,,
Dark Nemesis,Minion,,,,,,,,,,
Red Synja,Minion,,,,,,,,,//,
Jax Truesight,Minion,,,,,,/,+,,,
Pandora,Minion,,,,,,,,,,
Paddo,Minion,,,,,,,+,,,
Grailmaster,Minion,,,//,,,,,,,
Astral Crusader,Minion,,,,,,,,,,
Nebula,Minion,Golem,,,,,,,,,
Khymera,Minion,,,,,,,,//,,
Zurael the Lifegiver,Minion,,,+,,,,+,,,
Worldcore Golem,Minion,Golem,,,,,,,,,
Argeon Highmayne,General,,,,,,,,,,
Zir'An Sunforge,General,,,,,,,,,,
Brome Warcrest,General,,,,,,,,,,
Lionheart Blessing,Spell,,,,,,,,,,
Beam Shock,Spell,,,,,,,,,,
Sunstone Bracers,Artifact,,,,+,,,,,,
Silverguard Squire,Minion,,,++,,,,,,,
Sundrop Elixir,Spell,,,,,,/,,,,
Auryn Nexus,Spell,,,,,,/,,,,
True Strike,Spell,,,,,,,,,,
Aegis Barrier,Spell,,,,,,,,,,
Aerial Rift,Spell,,,,,,,,,,
Magnetize,Spell,,,,,,,,,,
Windblade Adept,Minion,,,+,,,,,,,
Sunstone Templar,Minion,,,+,,,,,,,
Lightchaser,Minion,,,+,,,,,,,
Azurite Lion,Minion,,/,+,,,,,,,
Tempest,Spell,,,,,,,,,,
Lasting Judgement,Spell,,++,,,,,,,,
War Surge,Spell,,+,,,,,,,,
Martyrdom,Spell,,,,,,,,,,
Sun Bloom,Spell,,,,,,,,,,
Divine Bond,Spell,,+,,,,,,,,
Silverguard Knight,Minion,,,,,,+,,,,
Arclyte Sentinel,Minion,,++,,,,,+,,,
Skywind Glaives,Artifact,,++,,+,,/,,,,
Lysian Brawler,Minion,,/,,,,,,,,
Suntide Maiden,Minion,,,,,,,,,,
Sunriser,Minion,,,,,,,,,,
Holy Immolation,Spell,,,,,,/,,,,
Decimate,Spell,,,,,,/,,,,
Arclyte Regalia,Artifact,,,,+,,,,,,
Second Sun,Minion,,,,,,,,,,
Ironcliffe Guardian,Minion,,,,,,+,,,,
Circle of Life,Spell,,,,,,,,,,
Elyx Stormblade,Minion,,,,,,+,,,,
Grandmaster Z'ir,Minion,,/,,,,,,,,
Kaleos Xaan,General,,,,,,,,,,
Reva Eventide,General,,,,,,,,,,
Shidai Stormblossom,General,,,,,,,,,,
Mana Vortex,Spell,,,,,,,,,,
Inner Focus,Spell,,,,,,,,,,
Juxtaposition,Spell,,,,,,,,,,
Heartseeker,Minion,,,++,,,,,,,
Saberspine Seal,Spell,,++,,,,,,,,
Kage Lightning,Spell,,,,,,,,,,
Ghost Lightning,Spell,,,,,,,,,,
Ancestral Divination,Spell,,,//,,,,,,,
Artifact Defiler,Spell,,,,,,,,,,
Mist Walking,Spell,,,,,,,,,,
Mask of Shadows,Artifact,,,,+,,/,,,,
Kaido Assassin,Minion,,,+,,,/,,,,
Chakri Avatar,Minion,Arcanyst,,+,,,,,,,
Celestial Phantom,Minion,,,+,,,,+,,,
Tusk Boar,Minion,,,+,,,,,,,
Mist Dragon Seal,Spell,,+,,,,,,,,
Phoenix Fire,Spell,,,,,,,,,,
Eight Gates,Spell,,,,,,,,,,
Deathstrike Seal,Spell,,,,,,/,,,,
Bloodrage Mask,Artifact,,,,+,,,,,,
Widowmaker,Minion,,,,,,,,,,
Gore Horn,Minion,,,,,,/,,,,
Jade Monk,Minion,,,,,,,,,,
Lantern Fox,Minion,,,,,,,,,,
Twin Strike,Spell,,,,,,,,,,
Onyx Bear Seal,Spell,,,,,,,,,,
Killing Edge,Spell,,+++,,,,,,,,
Cyclone Mask,Artifact,,,,+,,,,,,
Four Winds Magus,Minion,Arcanyst,,,,,,,,,
Keshrai Fanblade,Minion,,,,,,,+,,,
Heaven's Eclipse,Spell,,,,,,,,,,
Scarlet Viper,Minion,,,,,,,,,,
Hamon Bladeseeker,Minion,,,,,,,,,,
Storm Kage,Minion,,,,,,,,,,
Spiral Technique,Spell,,,,,,,,,,
Zirix Starstrider,General,,,,,,,,,,
Scioness Sajj,General,,,,,,,,,,
Ciphyron Ascendant,General,,,,,,,,,,
Siphon Energy,Spell,,,,,,,,,,
Rasha's Curse,Spell,,,,,,,,,,
Fountain of Youth,Spell,,,,,,,,,,
Blindscorch,Spell,,,,,,,,,,
Aurora's Tears,Spell,,,,///,,,,,,
Scion's First Wish,Spell,,+,,,,,,,,
Dunecaster,Minion,Dervish,,+,,,,+,,,
Orb Weaver,Minion,Dervish,,++,,,,+,,,
Pyromancer,Minion,,,+,,,/,,,,
Ethereal Obelysk,Minion,Structure,,+,,,,,,,
Imperial Saboteur,Minion,,,+,,,,+,,,
Sand Trap,Spell,,,,,,,,,,
Scion's Second Wish,Spell,,,,,,,,,,
Rasha's Curse,Spell,,,,,,,,,,
Bone Swarm,Spell,,,,,,,,,,
Staff Of Y'kir,Artifact,,,,+,,,,,,
Fireblaze Obelysk,Minion,Structure,,,,,,,,,
Windstorm Obelysk,Minion,Structure,,,,,,,,,
Portal Guardian,Minion,,,//,,,,,,,
Syzygy,Spell,,++,,,,/,,,,
Astral Phasing,Spell,,,,,,/,,,,
Entropic Decay,Spell,,,,,,/,,,,
Scion's Third Wish,Spell,,,,,,,,,,
Inner Oasis,Spell,,,,,,,,,,
Wildfire Ankh,Artifact,,,,+,,,,,,
Wind Shrike,Minion,,,,+,,,,,,
Sand Howler,Minion,Dervish,,,,,//,,,,
Mirage Master,Minion,,,,,,,+,,,
Hexblade,Artifact,,,,+,,,,,,
Starfire Scarab,Minion,,,,,,/,,,,
Star's Fury,Spell,,,,,,,,,,
Aymara Healer,Minion,,,,,,+,,,,
Oserix,Minion,,,,,,/,,,,
Dominate Will,Spell,,,,,,,,,,
Time Maelstrom,Spell,,,,,,,,,,
Lilithe Blightchaser,General,,,,,,,,,,
Cassyva Soulreaper,General,,,,,,,,,,
Maehv Skinsolder,General,,,,,,,,,,
Darkfire Sacrifice,Spell,,,,,,,,,,
Abyssal Crawler,Minion,,,++,,,,,,,
Void Pulse,Spell,,,,,,,,,,
Grasp of Agony,Spell,,,,,,,,,,
Consuming Rebirth,Spell,,,,,,,,,,
Horn of the Forsaken,Artifact,,,,+,,,,,,
Blood Siren,Minion,,,+,,,,+,,,
Darkspine Elemental,Minion,,,+,,,,,,,
Gloomchaser,Minion,,,+,,,/,+,,,
Daemonic Lure,Spell,,,,,,,,,,
Soulshatter Pact,Spell,,++,,,,,,,,
Spectral Blade,Artifact,,,,+,,,,,,
Shadow Watcher,Minion,,,,,,,,,,
Nightsorrow Assassin,Minion,,,,,,,+,,,
Wraithling Fury,Spell,,,,,,,,,,
Deathfire Crescendo,Spell,,++++,,,,,,,,
Rite Of The Undervault,Spell,,,,,,,,,,
Ritual Banishing,Spell,,,,,,,,,,
Shadow Reflection,Spell,,+++,,,,,,,,
Wraithling Swarm,Spell,,,,,,/,,,,
Soul Grimoire,Artifact,,,,+,,,,,,
Abyssal Juggernaut,Minion,,,,,,/,,,,
Bloodmoon Priestess,Minion,,,,,,,,,,
Aphotic Devourer,Minion,,,,,,,+,,,
Black Solus,Minion,,,,,,/,+,,,
Breath Of The Unborn,Spell,,,,,,/,,,,
Dark Terminus,Spell,,,,,,/,,,,
Dark Seed,Spell,,,,,,,,,,
Shadowdancer,Minion,,,,,,,,,,
Reaper of the Nine Moons,Minion,,,,,,,,,,
Nether Summoning,Spell,,,,,,/,,,,
Vorpal Reaver,Minion,,/,,,,,,,,
Spectral Revenant,Minion,,,,,,,,,,
Shadow Nova,Spell,,,,,,//,,,,
Vaath the Immortal,General,,,,,,,,,,
Starhorn the Seeker,General,,,,,,,,,,
Ragnora the Relentless,General,,,,,,,,,,
Dampening Wave,Spell,,,,,,,,,,
Flash Reincarnation,Spell,,,,,,,,,,///
Mana Burn,Spell,,,,,,,,,,
Greater Fortitude,Spell,,++,,,,,,,,
Iridium Scale,Artifact,,,,+,,,,,,
Phalanxar,Minion,,,+,,,,,,,
Kujata,Minion,,,+++,,,,,,,
Young Silithar,Minion,,,+,,,/,,,,
Diretide Frenzy,Spell,,+/,,,,,,,,
Tremor,Spell,,,,,,,,,,
Amplification,Spell,,++,,,,,,,,
Natural Selection,Spell,,/,,,,,,,,
Mind Steal,Spell,,,,,,,,,,
Twin Fang,Artifact,,,,+,,/,,,,
Earth Walker,Minion,,,,,,,,,,
Primordial Gazer,Minion,,++,,,,,+,,,
Vindicator,Minion,,,,,,/,,,,
Chrysalis Burst,Spell,,,,,,/,,,,
Kinetic Equilibrium,Spell,,++,,,,,,,,//
Grimrock,Minion,,,,,,,,,,
Elucidator,Minion,,,,,,,,,,
Veteran Silithar,Minion,,,,,,/,,,,
Earth Sphere,Spell,,,,,,,,,,
Plasma Storm,Spell,,,,,,,,,,
Egg Morph,Spell,,,,,,,,,,
Adamantite Claws,Artifact,,,,+,,,,,,
Kolossus,Minion,,,,,,,,,,
Spirit Harvester,Minion,,,,,,,,,,
Metamorphosis,Spell,,,,,,,,,,
Makantor Warbeast,Minion,,/,,,,,,,,
Fractal Replication,Spell,,/,,,,,,,,
Unstable Leviathan,Minion,,+,,,,,,,,
Silithar Elder,Minion,,,,,,/,,,,
Bounded Lifeforce,Spell,,,,,,,,,,
Faie Bloodwing,General,,,,,,,,,,
Kara Winterblade,General,,,,,,,,,,
Ilena Cryobyte,General,,,,,,,,,,
Flash Freeze,Spell,,,,,,,,,,
Polarity,Spell,,++,,,,,,,,
Snowchaser,Minion,Vespyr,,++,,,,,,,
Blazing Spines,Spell,,,,,,/,,,,
Aspect of the Fox,Spell,,,,,,,,,,
Winterblade,Artifact,,,,+,,,,,,
Crystal Cloaker,Minion,Vespyr,,+,,,,,,,
Crystal Wisp,Minion,,,+,,,,,,,
Borean Bear,Minion,Vespyr,,+,,,,,,,
Hearth-Sister,Minion,,,+,,,,+,,,
Bonechill Barrier,Spell,,,,,,,,,,
Chromatic Cold,Spell,,,,,,,,,,
Frostfire,Spell,,,,,,,,,,
Boundless Courage,Spell,,++,,,,,,,,
Mesmerize,Spell,,,,,,,,,,
Mark of Solitude,Spell,,++,,,,/,,,,
Aspect of the Wyrm,Spell,,,,,,,//,,,
Hailstone Prison,Spell,,,,,,,/,,,
Coldbiter,Artifact,,,,+,,,,,,
Fenrir Warmaster,Minion,,,,,,,,,,
Wolfraven,Minion,,/,,,,,,,,
Glacial Elemental,Minion,Vespyr,,,,,,,,,
Gravity Well,Spell,,,,,,,,,,
Cryogenesis,Spell,,,,,,,,,,
Snowpiercer,Artifact,,,,+,,,,,,
Razorback,Minion,,++,,,,,+,,,
Voice of the Wind,Minion,,,/,,,,,,,
Avalanche,Spell,,,,,,,,,,/
Spirit of the Wild,Spell,,,,,,,,,,
Draugar Lord,Minion,Vespyr,,,,,,+,,,
Arctic Displacer,Minion,Vespyr,,,,,/,,,,
Frosthorn Rhyno,Minion,,,,,,,,,,
Aspect of the Mountains,Spell,,,,,,,,,,
Ancient Grove,Minion,,,,,,++,+,,,
"""

spirit_island = """Spirit,Complexity,Disease manipulation,Badlands manipulation,Wilds manipulation,AOE damage,Presence mobility,Gift of energy,Gift of elements,Gift of presence,Invader action skipping,Presence destruction,Beast manipulation,Dahan manipulation,Pushing invaders,Strife manipulation,Blight manipulation
Lightning's Swift Strike,LOW,,,,+,,,,,,,,,,,
River Surges in Sunlight,LOW,,,,,,+,,,,,,,+,,
Shadows Flicker Like Flame,LOW,,,,,,,,,,,,,+,,
Vital Strength of the Earth,LOW,,,,,,,/,,,,,/,,,+
A Spread of Rampant Green,MODERATE,,,,+,,,,+/,+,,,/,+,,+
Thunderspeaker,MODERATE,,,,,,,,,+,+,,,,,
Bringer of Dreams and Nightmares,HIGH,,,,,,,+,,,,,+/,+,,
Ocean's Hungry Grasp,HIGH,,,,,,+/,,,,,,/,+,,
Keeper of the Forbidden Wilds,MODERATE,,,+/,,/,+/,,/,,,,,+,,+/
Sharp Fangs Behind the Leaves,MODERATE,,,,,,,,,,,,+,+,,
Heart of the Wildfire,HIGH,,,,,/,+/,/,/,+,+,+/,,+,,+/
Serpent Slumbering Beneath the Island,HIGH,,,,,/,+,+,+/,,,+,+,+,,
Grinning Trickster Stirs Up Trouble,MODERATE,,,,,,,,,,,,,,+/,/
Lure of the Deep Wilderness,MODERATE,+/,+/,+/,/,,,,,,,+/,+,,,
Many Minds Move as One,MODERATE,,,,,+,,,,,,+/,,,,
Shifting Memory of Ages,MODERATE,,,,,,,+,,,,+/,,,,
Stone's Unyielding Defiance,MODERATE,,+,,,,/,/,/,,,,,,,+/
Volcano Looming High,MODERATE,,,,,,,,/,,,,,,,/
Shroud of Silent Mist,HIGH,,,,,,,,,,+,,+,,,
Vengeance as a Burning Plague,HIGH,+/,,,,,,,,,,,,,,
Fractured Days Split the Sky,VERY HIGH,,,,,,,,,,/,,,,,
Starlight Seeks Its Form,VERY HIGH,,,,,,,,,+/,,,,,,
Downpour Drenches the World,HIGH,,,,,,,,,,,,,,,
Finder of Paths Unseen,VERY HIGH,,,,/,,,,,,,,,,,
Devouring Teeth Lurk Underfoot,LOW,,,,,,,,,,,,,,,
Eyes Watch from the Trees,LOW,,,,,,,,,,,,,,,
Fathomless Mud of the Swamp,LOW,,,,,,,,,,,,,,,
Rising Heat of Stone and Sand,LOW,,,,,,,,,,,,,,,
Sun-Bright Whirlwind,LOW,,,,,,,,,,,,,,,
Ember-Eyed Behemoth,MODERATE,,,,,,,,,,,,,,,
Towering Roots of the Jungle,MODERATE,,,,,,,,,,,,,,,
Hearth-Vigil,MODERATE,,,,,,,,,,,,,,,
Breath of Darkness Down Your Spine,HIGH,,,,/,+,,,,,,,,,,
Relentless Gaze of the Sun,HIGH,,,,,,,,,,,,,,,
Wandering Voice Keens Delirium,HIGH,,,,,,,,,,+,,,,+,
Wounded Waters Bleeding,HIGH,,,,,,,,,,,,,,,
Dances Up Earthquakes,VERY HIGH,,,,,,,,,,+,+/,+/,,,
"""