module Examples exposing (..)

botc = """Role,Type,Starting info role (good),Once per game role (good),Drunkenness or Poisoning,Demon kill immunity,Demon kill protection,Reason to visit storyteller,Explanation for failed execution,Reason for outsiders to hide,Demon mobility / Multiple demons,Free evil bluffs
Noble,Townsfolk,+,,,,,,,,,
Investigator,Townsfolk,+,,,,,,,,,
Chef,Townsfolk,+,,,,,,,,,
Washerwoman,Townsfolk,+,,,,,,,,,
Clockmaker,Townsfolk,+,,,,,,,,/,
Librarian,Townsfolk,+,,,,,,,,,
Grandmother,Townsfolk,+,,,,,,,,,
Bounty Hunter,Townsfolk,+,,,,,,,,/,
Pixie,Townsfolk,+,,,,,,,,,
Empath,Townsfolk,,,,,,,,,,
Sailor,Townsfolk,/,/,++,+,,,++//,,,
General,Townsfolk,,,,,,,,,,
Preacher,Townsfolk,,,,,,,,,,
Chambermaid,Townsfolk,,,,,,,,,/,
Balloonist,Townsfolk,,,,,,,,,/,
King,Townsfolk,,,,,,,,,,++
Dreamer,Townsfolk,,,,,,,,,/,
Fortune Teller,Townsfolk,,,,,,,,,/,
Mathematician,Townsfolk,,,//,//,,,,,,
Snake Charmer,Townsfolk,,,+,,,,,,+/,
Cult Leader,Townsfolk,,,,,,,,,,
Flowergirl,Townsfolk,,,,,,,,,/,
Town Crier,Townsfolk,,,,,,,,,,
Oracle,Townsfolk,,,,,,,,,,
Undertaker,Townsfolk,/,,,,,,,,/,
Innkeeper,Townsfolk,/,/,++,,++,,,,,
Gambler,Townsfolk,,,,,///,,,,,
Monk,Townsfolk,,,,,+,,,,,
Lycanthrope,Townsfolk,/,,,,++,,,,,
Exorcist,Townsfolk,,,,,,,,,/,
Gossip,Townsfolk,,,,,/,,,,,
Savant,Townsfolk,,,,,,,,,,
Amnesiac,Townsfolk,,,,,,+/,,,,
Juggler,Townsfolk,,+,,,/,,,,,
Nightwatchman,Townsfolk,,+,,,,,,,,
Engineer,Townsfolk,,+,,,,,,,,
Artist,Townsfolk,,+,,,,+/,,,,
Courtier,Townsfolk,,+,+,,,,,,,
Fisherman,Townsfolk,,+,,,,+/,,,,
Slayer,Townsfolk,,+,,,,,,,//,
Professor,Townsfolk,/,+/,,,,,,,,
Seamstress,Townsfolk,,+,,,,,,,,
Philosopher,Townsfolk,/,+/,+,,,,,,,
Huntsman,Townsfolk,,+,,,,,,,,++
Soldier,Townsfolk,,,,+,,,,,,
Fool,Townsfolk,,+,,+,,,+/,,,
Pacifist,Townsfolk,,,,,,,+/,,,
Alchemist,Townsfolk,,,,,,,,,,
Tea Lady,Townsfolk,,,,,,,+/,,,
Sage,Townsfolk,,,,,,,,,//,
Farmer,Townsfolk,,,,,,,,,,
Magician,Townsfolk,,,,,,,,,/,+///
Ravenkeeper,Townsfolk,,,,,,,,,/,
Choirboy,Townsfolk,,,,,,,,,///,
Virgin,Townsfolk,,,,,,,,,,
Poppy Grower,Townsfolk,,,,,,,,,/,+///
Minstrel,Townsfolk,,,,,,,,,,
Mayor,Townsfolk,,,,+,,,,,,
Atheist,Townsfolk,,,,,,,,,,+
Cannibal,Townsfolk,/,/,+,,,,,,,
Snitch,Outsider,,,,,,,,/,,++
Butler,Outsider,,,,,,,,/,,
Goon,Outsider,,,+,,,,,,,
Acrobat,Outsider,,,/,,,,,/,,
Puzzlemaster,Outsider,,+,+,,,+/,,,/,
Tinker,Outsider,,,,,,,,/,,
Saint,Outsider,,,,,,,,//,,
Sweetheart,Outsider,,,+,,,,,,,
Recluse,Outsider,,,,,,,,/,,
Mutant,Outsider,,,,,,,,,,
Heretic,Outsider,,,,,,,,,,
Damsel,Outsider,,,,,,,,,,+
Klutz,Outsider,,,,,,,,,,
Drunk,Outsider,,,,,,,,,,
Golem,Outsider,,+,,,,,,/,,
Moonchild,Outsider,,,,,,,,,,
Barber,Outsider,,,,,,,,,+/,
Politician,Outsider,,,,,,,,,,
Lunatic,Outsider,,,,,,,,,,+
Godfather,Minion,,,,,,,,+,,+
Widow,Minion,/,,+,,,,,,,+++
Poisoner,Minion,,,++,,,,,,,
Devil's Advocate,Minion,,,,,,,+/,,,
Witch,Minion,,,,,,,,,,
Spy,Minion,,,,,,,,,,+++
Cerenovus,Minion,,,,,,,,,,
Fearmonger,Minion,,,,,,,,,,
Pit-Hag,Minion,,,,,,,,,+/,
Psychopath,Minion,,,,,,,,,,
Assassin,Minion,,,,,,,,,,
Baron,Minion,,,,,,,,,,
Mezepheles,Minion,,,,,,,,,,
Goblin,Minion,,,,,,,,,,+
Scarlet Woman,Minion,,,,,,,,,+/,
Mastermind,Minion,,,,,,,,,,
Evil Twin,Minion,,,,,,,,,,+
Boomdandy,Minion,,,,,,,,,,
Marionette,Minion,,,,,,,,,,+
Pukka,Demon,,,+,/,,,,,,
Lil' Monsta,Demon,,,,,,,,,+++/,///
Lleech,Demon,,,+,,,,+/,,,
No Dashii,Demon,,,++,,,,,,,
Imp,Demon,,,,,,,,,+/,
Shabaloth,Demon,/,,,,,,,,,
Po,Demon,,,,,,,,,,
Zombuul,Demon,,,,,,,,,,
Al-Hadikhia,Demon,/,,,//,,,,,,
Vigormortis,Demon,,,+,,,,,,,
Fang Gu,Demon,,,,,,,,+++,+/,
Vortox,Demon,/,,,,,,,,,
Legion,Demon,,,,,,,,,+/,///
Leviathan,Demon,,,,,,,,,,
Riot,Demon,///,,,,,,,,,
"""

spirit_island = """Spirit,Complexity,Disease manipulation,Badlands manipulation,Wilds manipulation,AOE damage,Presence mobility,Gift of energy,Gift of elements,Gift of presence,Invader action skipping,Presence destruction,Beast manipulation,Dahan manipulation,Pushing invaders,Strife manipulation,Blight manipulation
Lightning's Swift Strike,LOW,,,,+,,,,,,,,,,,
River Surges in Sunlight,LOW,,,,,,+,,,,,,,+,,
Shadows Flicker Like Flame,LOW,,,,,,,,,,,,,+,,
Vital Strength of the Earth,LOW,,,,,,,/,,,,,/,,,+
A Spread of Rampant Green,MODERATE,,,,+,,,,+/,+,,,/,+,,+
Thunderspeaker,MODERATE,,,,,,,,,+,+,,,,,
Bringer of Dreams and Nightmares,HIGH,,,,,,,+,,,,,+/,+,,
Ocean's Hungry Grasp,HIGH,,,,,,+/,,,,,,/,+,,
Keeper of the Forbidden Wilds,MODERATE,,,+/,,/,+/,,/,,,,,+,,+/
Sharp Fangs Behind the Leaves,MODERATE,,,,,,,,,,,,+,+,,
Heart of the Wildfire,HIGH,,,,,/,+/,/,/,+,+,+/,,+,,+/
Serpent Slumbering Beneath the Island,HIGH,,,,,/,+,+,+/,,,+,+,+,,
Grinning Trickster Stirs Up Trouble,MODERATE,,,,,,,,,,,,,,+/,/
Lure of the Deep Wilderness,MODERATE,+/,+/,+/,/,,,,,,,+/,+,,,
Many Minds Move as One,MODERATE,,,,,+,,,,,,+/,,,,
Shifting Memory of Ages,MODERATE,,,,,,,+,,,,+/,,,,
Stone's Unyielding Defiance,MODERATE,,+,,,,/,/,/,,,,,,,+/
Volcano Looming High,MODERATE,,,,,,,,/,,,,,,,/
Shroud of Silent Mist,HIGH,,,,,,,,,,+,,+,,,
Vengeance as a Burning Plague,HIGH,+/,,,,,,,,,,,,,,
Fractured Days Split the Sky,VERY HIGH,,,,,,,,,,/,,,,,
Starlight Seeks Its Form,VERY HIGH,,,,,,,,,+/,,,,,,
Downpour Drenches the World,HIGH,,,,,,,,,,,,,,,
Finder of Paths Unseen,VERY HIGH,,,,/,,,,,,,,,,,
Devouring Teeth Lurk Underfoot,LOW,,,,,,,,,,,,,,,
Eyes Watch from the Trees,LOW,,,,,,,,,,,,,,,
Fathomless Mud of the Swamp,LOW,,,,,,,,,,,,,,,
Rising Heat of Stone and Sand,LOW,,,,,,,,,,,,,,,
Sun-Bright Whirlwind,LOW,,,,,,,,,,,,,,,
Ember-Eyed Behemoth,MODERATE,,,,,,,,,,,,,,,
Towering Roots of the Jungle,MODERATE,,,,,,,,,,,,,,,
Hearth-Vigil,MODERATE,,,,,,,,,,,,,,,
Breath of Darkness Down Your Spine,HIGH,,,,/,+,,,,,,,,,,
Relentless Gaze of the Sun,HIGH,,,,,,,,,,,,,,,
Wandering Voice Keens Delirium,HIGH,,,,,,,,,,+,,,,+,
Wounded Waters Bleeding,HIGH,,,,,,,,,,,,,,,
Dances Up Earthquakes,VERY HIGH,,,,,,,,,,+,+/,+/,,,
"""